import type { NextPage } from "next";
import Head from "next/head";
import Board from "../components/Board";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>NextChess</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="px-1 py-2 sm:px-3">
        <h1 className="text-2xl font-semibold">
          <a href="/">NextChess</a>
        </h1>
      </header>
      <main className="flex justify-center py-2">
        <Board />
      </main>
    </div>
  );
};

export default Home;
